:: Echo %1
dotnet tool install -g dotnet-reportgenerator-globaltool
rd coverage /S /Q
cd ..
FOR /D /r %%G in ("tests/*.Tests") DO (
	Echo We found %%~nxG
	cd %%~nxG
	dir /b /a-d
	rd TestResults /S /Q
	dotnet test --collect:"XPlat Code Coverage" --filter 
	cd ..
)

:: Retarget back to the current directory
cd /D "%~dp0"

:: Hack with class filters because when run locally the coverage tool includes tests in coverage but doesn't when run in GHA
reportgenerator "-reports:../tests/**/coverage.cobertura.xml" "-targetdir:./coverage" "-reporttypes:Html" "-classfilters:-System.Runtime.CompilerServices;-Microsoft.AspNetCore.OpenApi.Generated;-AutoGeneratedProgram;-Azure.Local.ApiService.Tests.Component.*;-*.TestHelper;-*.ApplicationUnitTests"
start ./coverage/index.html

pause